name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x
      - name: Setup RSpec
        run: |
          bundle
      - name: RSpec Report
        run: bin/rspec
